/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import fns.DigitValidator;
import fns.StudentDBOP;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class editprofileFrame extends javax.swing.JFrame {

    public editprofileFrame() {
         super("STUDENT PROFILE EDIT FRAME "+operationsFrame.studentname);
        ArrayList<String> studentdata=new StudentDBOP().getStudentData(operationsFrame.studentname);
        System.out.println("studentdata"+studentdata);
        String name = studentdata.get(0);
String dob = studentdata.get(1);
String mobno = studentdata.get(2);
String email = studentdata.get(3);
String dept = studentdata.get(4);
String college = studentdata.get(5);
String username = studentdata.get(6);
String password = studentdata.get(7);


        String st[]=dob.split("-");
        String date=st[0];
        String month=st[1];
        String year=st[2];

        initComponents();
         jTextField5.setEditable(false);
        jTextField5.setText(username);
        jTextField6.setText(date);
        jTextField7.setText(month);
        jTextField8.setText(year);
        jComboBox1.setSelectedItem(dept);

        jTextField4.setText(college);
        jTextField3.setText(email);
        jTextField2.setText(mobno);
        jTextField1.setText(name);
        jPasswordField2.setText(password);
                jPasswordField1.setText(password);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField6 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-name-50.png"))); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(880, 270, 220, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-calendar-39.png"))); // NOI18N
        jLabel3.setText("Date of Birth");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(880, 321, 220, 39);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-call-39.png"))); // NOI18N
        jLabel4.setText("Mobile No");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(880, 380, 210, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-email-40.png"))); // NOI18N
        jLabel5.setText("Email id");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(880, 440, 200, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-department-40.png"))); // NOI18N
        jLabel6.setText("Department");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(880, 500, 190, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-college-40.png"))); // NOI18N
        jLabel7.setText("College");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(880, 550, 210, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-user-40.png"))); // NOI18N
        jLabel8.setText("Username");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(880, 610, 210, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/padlock (1).png"))); // NOI18N
        jLabel9.setText("Password");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(880, 660, 200, 40);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/padlock (1).png"))); // NOI18N
        jLabel10.setText("Confirm Password");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(870, 720, 250, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1150, 810, 170, 40);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1.setOpaque(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(1140, 260, 370, 40);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(null);
        jTextField2.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField2.setOpaque(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(1140, 370, 370, 40);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(null);
        jTextField3.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField3.setOpaque(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(1140, 430, 360, 40);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setBorder(null);
        jTextField4.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField4.setOpaque(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(1150, 550, 350, 30);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setBorder(null);
        jTextField5.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField5.setOpaque(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(1140, 600, 360, 40);

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(null);
        jPasswordField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jPasswordField1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPasswordField1.setOpaque(false);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(1140, 662, 370, 28);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(1140, 330, 60, 30);

        jPasswordField2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setBorder(null);
        jPasswordField2.setCaretColor(new java.awt.Color(255, 255, 255));
        jPasswordField2.setOpaque(false);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(1140, 720, 360, 30);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(1220, 330, 70, 30);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(1310, 330, 120, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Engineering", "Information Technology Engineering", "Mechanical Engineering", "Civil Engineering", "Electronics and Telecommunication Engineering", "Electrical Engineering", "Artificial Intelligence and Data Science Engineering", "Computer Science and Engineering", "Instrumentation Engineering", "Biomedical Engineering", "Chemical Engineering", "Environmental Engineering", "Aerospace Engineering", "Automobile Engineering", "Production Engineering", "Structural Engineering", " " }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(1140, 490, 360, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_images/6.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        jMenuBar1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(50, 50));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user (1).png"))); // NOI18N
        jMenu1.setText("Manage Profile");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-user-40.png"))); // NOI18N
        jMenuItem1.setText("Edit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/folder (1).png"))); // NOI18N
        jMenu2.setText("Upload");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cloud-storage (1).png"))); // NOI18N
        jMenuItem2.setText("Uplaod Notes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/folder-2.png"))); // NOI18N
        jMenuItem3.setText("View/Edit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-download-16.png"))); // NOI18N
        jMenu3.setText("Download");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/folder (1).png"))); // NOI18N
        jMenuItem4.setText("Download Notes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/webpage-list (1).png"))); // NOI18N
        jMenuItem5.setText("Download History");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button (1).png"))); // NOI18N
        jMenu4.setText("Logout");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user-logout (1).png"))); // NOI18N
        jMenuItem6.setText("Exit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String name=jTextField1.getText(); 
String date=jTextField6.getText(); 
String month=jTextField7.getText();
String year=jTextField8.getText(); 
String mobno=jTextField2.getText(); 
String email=jTextField3.getText();
String dept = (String) jComboBox1.getSelectedItem();
String college=jTextField4.getText();
String username=jTextField5.getText(); 
String pass=jPasswordField1.getText();
String conpass=jPasswordField2.getText();

if (name.isEmpty())
            JOptionPane.showMessageDialog(null, "Name Can Not Be Empty");
        //Name Validation Completed
        
        else if(date.isEmpty())
            JOptionPane.showMessageDialog(null, "Date Should Not Be Empty");
        else if(date.length()!=2)
            JOptionPane.showMessageDialog(null, "Date Should be of Two Digits");
        else if(!new DigitValidator().inDigit(date))
            JOptionPane.showMessageDialog(null, "Date Should Contains Digit only");
        else if(!(Integer.parseInt(date)>=1 && Integer.parseInt(date)<=31))
            JOptionPane.showMessageDialog(null, "Date Should be between 1 to 31");
        // Date Validation Completed
        
        else if(month.isEmpty())
            JOptionPane.showMessageDialog(null, "Month Should Not Be Empty");
        else if(month.length()!=2)
            JOptionPane.showMessageDialog(null, "Month Should be of Two Digits");
        else if(!new DigitValidator().inDigit(month))
            JOptionPane.showMessageDialog(null, "Month Should Contains Digit only");
        else if(!(Integer.parseInt(month)>=1 && Integer.parseInt(month)<=12))
            JOptionPane.showMessageDialog(null, "Month Should be between 1 to 12");
        //Month Validation Completed
        
        else if(year.isEmpty())
            JOptionPane.showMessageDialog(null, "Year Should Not Be Empty");
        else if(year.length()!=4)
            JOptionPane.showMessageDialog(null, "Year Should be of Four Digits");
        else if(!new DigitValidator().inDigit(year))
            JOptionPane.showMessageDialog(null, "Year Should Contains Digit only");
        // year Comp 
       
        else if(mobno.isEmpty())
            JOptionPane.showMessageDialog(null, "Mobilenum Should Not Be Empty");
        else if(mobno.length()!=10)
            JOptionPane.showMessageDialog(null, "mobilenum Should be of Ten Digits");
        else if(!new DigitValidator().inDigit(mobno))
            JOptionPane.showMessageDialog(null, "Mobilenum Should Contains Digits only");
        //Mobilenum Comp
        
         else if(email.isEmpty())
            JOptionPane.showMessageDialog(null, "Email Should Not Be Empty");
        else if(!(email.contains(".") && email.contains("@")))
            JOptionPane.showMessageDialog(null, "Email id is not valid");
        //Email Comp
        else if(dept.isEmpty())
            JOptionPane.showMessageDialog(null, "Department Should Not Be Empty");
        
        else if(college.isEmpty())
            JOptionPane.showMessageDialog(null, "College Should Not Be Empty");
      
        else if(username.isEmpty())
            JOptionPane.showMessageDialog(null, "Username Should Not Be Empty");
        //username Comp
        
        else if(pass.isEmpty())
            JOptionPane.showMessageDialog(null, "Password Should Not Be Empty");
        else if(pass.length()!=8)
            JOptionPane.showMessageDialog(null, "Password Should be of Eight Digits");
        // Password Comp 
        
        else if(conpass.isEmpty())
            JOptionPane.showMessageDialog(null, "Confirm Password Should Not Be Empty");
        else if(conpass.length()!=8)
            JOptionPane.showMessageDialog(null, "Confirm Password Should be of Eight Digits");
        else if(!pass.equals(conpass))
            JOptionPane.showMessageDialog(null, "Confirm Password Should not Equal to Password");
        //Confirm Password Comp
        
        else{
            
            name=name.trim();
            date=date.trim();
            month=month.trim();
            year=year.trim();
            mobno=mobno.trim();
            email=email.trim();
            dept=dept.trim();
            college=college.trim();
            username=username.trim();
            pass=pass.trim();
            conpass=conpass.trim();
            
            System.out.println("Name:"+name);
            System.out.println("Date:"+date);
            System.out.println("Month:"+month);
            System.out.println("Year:"+year);
            System.out.println("Mobile No.:"+mobno);
            System.out.println("Email ID:"+email);
            System.out.println("Department:"+dept);
            System.out.println("College:"+college);
            System.out.println("UserName:"+username);
            System.out.println("Password:"+pass);
            System.out.println("Confirm Password:"+conpass);
            
            Date dt = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat ("dd-MM_YYYY hh:mm:ss");
            String currenttime =sdf.format(dt);
            System.out.println("Current Date And Time :"+currenttime);

           String dob=date+"-"+month+"-"+year;
           StudentDBOP sdbop=new StudentDBOP();  
           if(sdbop.isStudentEdited(name, dob, mobno, email, dept, college, username, pass, currenttime))
              JOptionPane.showMessageDialog(null, "Student Credentials are Updated Successfully");
          else
               JOptionPane.showMessageDialog(null, "Error Occured !! Please try again later");
        } // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        editprofileFrame epf= new editprofileFrame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        epf.setVisible(true);
        epf.setSize(d);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
        uploadFrame upf= new uploadFrame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        upf.setVisible(true);
        upf.setSize(d);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
        UploadView_EditFrame upf= new UploadView_EditFrame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        upf.setVisible(true);
        upf.setSize(d);   // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
        DownloadFrame upf= new DownloadFrame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        upf.setVisible(true);
        upf.setSize(d);         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.dispose();
        downloadhistoryFrame upf= new downloadhistoryFrame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        upf.setVisible(true);
        upf.setSize(d);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.dispose();
        loginFrame lf= new loginFrame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        lf.setVisible(true);
        lf.setSize(d);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editprofileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editprofileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editprofileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editprofileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editprofileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
