/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import fns.DigitValidator;
import fns.StudentDBOP;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class signupFrame extends javax.swing.JFrame {

    /**
     * Creates new form signupFrame
     */
    public signupFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField6 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-name-50.png"))); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 200, 220, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-calendar-39.png"))); // NOI18N
        jLabel3.setText("Date of Birth");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 260, 220, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-call-39.png"))); // NOI18N
        jLabel4.setText("Mobile No");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 320, 210, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-email-40.png"))); // NOI18N
        jLabel5.setText("Email id");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 380, 200, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-department-40.png"))); // NOI18N
        jLabel6.setText("Department");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 450, 210, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-college-40.png"))); // NOI18N
        jLabel7.setText("College");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 510, 210, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-user-40.png"))); // NOI18N
        jLabel8.setText("Username");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(370, 570, 210, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/padlock (1).png"))); // NOI18N
        jLabel9.setText("Password");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(370, 630, 200, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/padlock (1).png"))); // NOI18N
        jLabel10.setText("Confirm Password");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(360, 690, 240, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-submit-document-60.png"))); // NOI18N
        jButton1.setText("Register");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 810, 250, 40);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-back-50.png"))); // NOI18N
        jButton3.setText("Back    ");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(60, 30, 170, 50);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(650, 190, 390, 40);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(null);
        jTextField2.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField2.setOpaque(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(650, 320, 390, 40);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(null);
        jTextField3.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField3.setOpaque(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(650, 380, 390, 40);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setBorder(null);
        jTextField4.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField4.setOpaque(false);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(650, 496, 400, 40);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setBorder(null);
        jTextField5.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField5.setOpaque(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(650, 566, 400, 40);

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(null);
        jPasswordField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jPasswordField1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPasswordField1.setOpaque(false);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(660, 630, 390, 30);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(650, 260, 70, 40);

        jPasswordField2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setBorder(null);
        jPasswordField2.setCaretColor(new java.awt.Color(255, 255, 255));
        jPasswordField2.setOpaque(false);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(660, 688, 390, 40);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(740, 260, 70, 40);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(830, 260, 100, 40);

        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Engineering", "Information Technology Engineering", "Mechanical Engineering", "Civil Engineering", "Electronics and Telecommunication Engineering", "Electrical Engineering", "Artificial Intelligence and Data Science Engineering", "Computer Science and Engineering", "Instrumentation Engineering", "Biomedical Engineering", "Chemical Engineering", "Environmental Engineering", "Aerospace Engineering", "Automobile Engineering", "Production Engineering", "Structural Engineering", " " }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(650, 440, 400, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_images/3.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String name=jTextField1.getText(); 
String date=jTextField6.getText(); 
String month=jTextField7.getText();
String year=jTextField8.getText(); 
String mobno=jTextField2.getText(); 
String email=jTextField3.getText();
String dept = (String) jComboBox1.getSelectedItem();
String college=jTextField4.getText();
String username=jTextField5.getText(); 
String pass=jPasswordField1.getText();
String conpass=jPasswordField2.getText();

if (name.isEmpty())
            JOptionPane.showMessageDialog(null, "Name Can Not Be Empty");
        //Name Validation Completed
        
        else if(date.isEmpty())
            JOptionPane.showMessageDialog(null, "Date Should Not Be Empty");
        else if(date.length()!=2)
            JOptionPane.showMessageDialog(null, "Date Should be of Two Digits");
        else if(!new DigitValidator().inDigit(date))
            JOptionPane.showMessageDialog(null, "Date Should Contains Digit only");
        else if(!(Integer.parseInt(date)>=1 && Integer.parseInt(date)<=31))
            JOptionPane.showMessageDialog(null, "Date Should be between 1 to 31");
        // Date Validation Completed
        
        else if(month.isEmpty())
            JOptionPane.showMessageDialog(null, "Month Should Not Be Empty");
        else if(month.length()!=2)
            JOptionPane.showMessageDialog(null, "Month Should be of Two Digits");
        else if(!new DigitValidator().inDigit(month))
            JOptionPane.showMessageDialog(null, "Month Should Contains Digit only");
        else if(!(Integer.parseInt(month)>=1 && Integer.parseInt(month)<=12))
            JOptionPane.showMessageDialog(null, "Month Should be between 1 to 12");
        //Month Validation Completed
        
        else if(year.isEmpty())
            JOptionPane.showMessageDialog(null, "Year Should Not Be Empty");
        else if(year.length()!=4)
            JOptionPane.showMessageDialog(null, "Year Should be of Four Digits");
        else if(!new DigitValidator().inDigit(year))
            JOptionPane.showMessageDialog(null, "Year Should Contains Digit only");
        // year Comp 
       
        else if(mobno.isEmpty())
            JOptionPane.showMessageDialog(null, "Mobilenum Should Not Be Empty");
        else if(mobno.length()!=10)
            JOptionPane.showMessageDialog(null, "mobilenum Should be of Ten Digits");
        else if(!new DigitValidator().inDigit(mobno))
            JOptionPane.showMessageDialog(null, "Mobilenum Should Contains Digits only");
        //Mobilenum Comp
        
         else if(email.isEmpty())
            JOptionPane.showMessageDialog(null, "Email Should Not Be Empty");
        else if(!(email.contains(".") && email.contains("@")))
            JOptionPane.showMessageDialog(null, "Email id is not valid");
        //Email Comp
        else if(dept.isEmpty())
            JOptionPane.showMessageDialog(null, "Department Should Not Be Empty");
        
        else if(college.isEmpty())
            JOptionPane.showMessageDialog(null, "College Should Not Be Empty");
      
        else if(username.isEmpty())
            JOptionPane.showMessageDialog(null, "Username Should Not Be Empty");
        //username Comp
        
        else if(pass.isEmpty())
            JOptionPane.showMessageDialog(null, "Password Should Not Be Empty");
        else if(pass.length()!=8)
            JOptionPane.showMessageDialog(null, "Password Should be of Eight Digits");
        // Password Comp 
        
        else if(conpass.isEmpty())
            JOptionPane.showMessageDialog(null, "Confirm Password Should Not Be Empty");
        else if(conpass.length()!=8)
            JOptionPane.showMessageDialog(null, "Confirm Password Should be of Eight Digits");
        else if(!pass.equals(conpass))
            JOptionPane.showMessageDialog(null, "Confirm Password Should not Equal to Password");
        //Confirm Password Comp
        
        else{
            
            name=name.trim();
            date=date.trim();
            month=month.trim();
            year=year.trim();
            mobno=mobno.trim();
            email=email.trim();
            dept=dept.trim();
            college=college.trim();
            username=username.trim();
            pass=pass.trim();
            conpass=conpass.trim();
            
            System.out.println("Name:"+name);
            System.out.println("Date:"+date);
            System.out.println("Month:"+month);
            System.out.println("Year:"+year);
            System.out.println("Mobile No.:"+mobno);
            System.out.println("Email ID:"+email);
            System.out.println("Department:"+dept);
            System.out.println("College:"+college);
            System.out.println("UserName:"+username);
            System.out.println("Password:"+pass);
            System.out.println("Confirm Password:"+conpass);
            
            Date dt = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat ("dd-MM_YYYY hh:mm:ss");
            String currenttime =sdf.format(dt);
            System.out.println("Current Date And Time :"+currenttime);

           String dob=date+"-"+month+"-"+year;
           StudentDBOP sdbop=new StudentDBOP();  
           if(sdbop.isStudentCreated(name, dob, mobno, email, dept, college, username, pass, currenttime))
               JOptionPane.showMessageDialog(null, "Succesfully client registered\nthank you very much");
           else
               JOptionPane.showMessageDialog(null, "Eroor Occured!!!\nPlease try again");

jTextField1.setText(""); 
jTextField2.setText(""); 
jTextField3.setText(""); 
jTextField4.setText(""); 
jTextField5.setText(""); 
jTextField6.setText(""); 
jTextField7.setText(""); 
jPasswordField1.setText("");
jPasswordField2.setText(""); 


        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();
       loginFrame lf= new loginFrame();
       Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
       lf.setVisible(true);
       lf.setSize(d);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
